import type { Metadata } from 'next'
import { Kanit, Inter } from 'next/font/google'
import './globals.css'
import { Header } from '@/components/shared/Header'
import { cn } from '@/lib/utils'
import localFont from 'next/font/local'
import { Footer } from '@/components/shared/Footer'
import { useUser } from '@/hooks/useUser'
import Link from 'next/link'

const inter = Inter({
  variable: '--font-inter',
  subsets: ['latin'],
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
})

const Satoshi = localFont({
  src: [
    {
      path: '../../public/fonts/satoshi.ttf',
      weight: '100 200 300 400 500 600 700 800 900',
    },
  ],
  variable: '--font-satoshi',
})

const kanit = Kanit({
  variable: '--font-kanit',
  subsets: ['latin'],
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  const { user } = useUser()

  return (
    <html lang="en">
      <body
        className={cn(
          kanit.variable,
          Satoshi.variable,
          inter.variable,
          inter.className,
          'flex min-h-screen w-full flex-col',
        )}
      >
        {!user && (
          <div className="w-full bg-black px-4 py-3 text-center font-satoshi text-sm font-medium text-white">
            Sign up and get 20% off to your first order.{' '}
            <Link
              href="/auth?authType=signup"
              className="font-semibold underline"
            >
              Sign Up Now
            </Link>
          </div>
        )}
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  )
}
