import type { Metadata } from 'next'
import { Kanit, Inter } from 'next/font/google'
import './globals.css'
import { Header } from '@/components/shared/Header'
import { cn } from '@/lib/utils'
import localFont from 'next/font/local'
import { Footer } from '@/components/shared/Footer'

const inter = Inter({
  variable: '--font-inter',
  subsets: ['latin'],
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
})

const Satoshi = localFont({
  src: [
    {
      path: '../../public/fonts/satoshi.ttf',
      weight: '100 200 300 400 500 600 700 800 900',
    },
  ],
  variable: '--font-satoshi',
})

const kanit = Kanit({
  variable: '--font-kanit',
  subsets: ['latin'],
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          kanit.variable,
          Satoshi.variable,
          inter.variable,
          inter.className,
          'flex min-h-screen w-full flex-col',
        )}
      >
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  )
}
